# Generated by Django 4.2.3 on 2023-07-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_subplanfeatures_subpl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subplanfeatures',
            name='subpl',
        ),
        migrations.AddField(
            model_name='subplanfeatures',
            name='subplan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.subplan'),
        ),
    ]
