# Generated by Django 4.2.3 on 2023-07-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_subplanfeatures_subpl_subplanfeatures_subplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='subPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subpl', models.ManyToManyField(to='polls.subplan')),
            ],
        ),
        migrations.DeleteModel(
            name='subPlanFeatures',
        ),
    ]
