# Generated by Django 4.2.3 on 2023-07-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_subplanfeature_delete_subplanfeatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='subPlanFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subplan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.subplan')),
            ],
        ),
        migrations.DeleteModel(
            name='subPlanFeature',
        ),
    ]
